### ISSUE TITLE
Support url() asset references in Markdown frontmatter

### ISSUE THREAD

**Issue by tantalic** [jakelazaroff/radish#5]
Radish supports assets references with `url()` for TOM, YAML and JSON content but does not support the use of `url()` in Markdown frontmater. It would be nice to support the use of assets within Markdown frontmatter.

**Comment by tantalic** [comment]
@jakelazaroff if you are open this change and external contributions I would be happy to work on this. If so, I'd appreciate any guidance on how you would like to see it implemented.

**Comment by jakelazaroff** [comment]
This should be fixed by https://github.com/jakelazaroff/radish/pull/6 ! Sorry for the delay.
